name: Fineract Publish to DockerHub
on:
  push:
    branches:
      - develop
    tags:
      - 1.*
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      - name: Get Git Hashes
        run: |
          echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "long_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: git_hashes

      - name: Build the Apache Fineract image
        run:  |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            TAGS="latest"
          else
            TAGS="${{ github.ref_name }}"
          fi

          ./gradlew --no-daemon --console=plain :fineract-provider:jib -x test -x cucumber \
            -Djib.to.auth.username=${{secrets.DOCKERHUB_USER}} \
            -Djib.to.auth.password=${{secrets.DOCKERHUB_TOKEN}} \
            -Djib.from.platforms=linux/amd64,linux/arm64 \
            -Djib.to.image=apache/fineract \
            -Djib.to.tags=$TAGS
